export const ROLLUP_TABLES = {
  stats: "daily_stats",
  pages: "daily_pages",
  referrers: "daily_referrers",
  countries: "daily_countries",
  regions: "daily_regions",
  cities: "daily_cities",
  browsers: "daily_browsers",
  os: "daily_os",
  devices: "daily_devices",
  agents: "daily_agents",
  visitors: "daily_visitors",
  sessions: "daily_sessions",
} as const;

export const ROLLUP_COLUMNS = {
  stats: {
    projectId: "project_id",
    date: "date",
    pageviews: "pageviews",
    entries: "entries",
    visitors: "visitors",
    sessions: "sessions",
  },
  pages: {
    projectId: "project_id",
    date: "date",
    path: "path",
    pageviews: "pageviews",
    entries: "entries",
  },
  referrers: {
    projectId: "project_id",
    date: "date",
    referrer: "referrer",
    pageviews: "pageviews",
  },
  countries: {
    projectId: "project_id",
    date: "date",
    countryCode: "country_code",
    visitors: "visitors",
  },
  regions: {
    projectId: "project_id",
    date: "date",
    countryCode: "country_code",
    region: "region",
    visitors: "visitors",
  },
  cities: {
    projectId: "project_id",
    date: "date",
    countryCode: "country_code",
    region: "region",
    city: "city",
    visitors: "visitors",
  },
  browsers: {
    projectId: "project_id",
    date: "date",
    browser: "browser",
    visitors: "visitors",
  },
  os: {
    projectId: "project_id",
    date: "date",
    os: "os",
    visitors: "visitors",
  },
  devices: {
    projectId: "project_id",
    date: "date",
    device: "device",
    visitors: "visitors",
  },
  agents: {
    projectId: "project_id",
    date: "date",
    category: "category",
    vendor: "vendor",
    harness: "harness",
    confidence: "confidence",
    visitors: "visitors",
  },
  visitors: {
    projectId: "project_id",
    date: "date",
    visitorId: "visitor_id",
    firstSeenAt: "first_seen_at",
  },
  sessions: {
    projectId: "project_id",
    date: "date",
    sessionId: "session_id",
    firstSeenAt: "first_seen_at",
  },
} as const;
